# docker-compose.yml (วางไว้ที่ root ของโปรเจกต์ ข้างเดียวกับ Dockerfile)

services:
  restaurant-service:
    build:
      context: ./restaurant
      dockerfile: Dockerfile
    image: restaurant-service:latest
    container_name: restaurant-service
    ports:
      - "8080:8080"
    volumes:
      # เก็บไฟล์ H2 database ถาวรใน volume
      - h2data:/app/data
    depends_on:
      - kafka
    networks:
      - backend
    environment:
      - SERVER_ADDRESS=0.0.0.0
  

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - backend

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
    ports:
      - "9000:9000"
    networks:
      - backend

volumes:
  h2data:

networks:
  backend:
    driver: bridge
